export const COUNTRIES: string[] = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'India',
  'Pakistan',
  'Nigeria',
  'Philippines',
  'Mexico',
  'Brazil',
  'China',
  'South Korea',
  'Japan',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'South Africa',
  'Egypt',
  'Kenya',
  'Ghana',
  'United Arab Emirates',
  'Saudi Arabia',
  'Bangladesh',
  'Vietnam',
  'Indonesia',
  'Ukraine',
  'Russia',
  'Poland',
  'Colombia',
  'Argentina',
  'Other',
]

export const US_STATES: string[] = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
  'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
  'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
  'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
  'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
  'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
  'West Virginia', 'Wisconsin', 'Wyoming',
]
