FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build:expert


FROM nginx:alpine

COPY --from=build /app/expert/dist /usr/share/nginx/html

COPY nginx-portal.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

