FROM node:20-alpine AS build

WORKDIR /app

COPY client-expert/package*.json ./

RUN npm ci

COPY client-expert/ ./client-expert/
COPY packages/ ./packages/

WORKDIR /app/client-expert

RUN npm run build:expert


FROM nginx:alpine

COPY --from=build /app/client-expert/expert/dist /usr/share/nginx/html

COPY client-expert/nginx-portal.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
